### ISSUE TITLE
CDMA device models for iPhone 6 and 6 plus are not specified

### ISSUE THREAD

**Issue by thndrkiss** [InderKumarRathore/DeviceUtil#18]
Hi,

I just noticed that the hardware model for iPhone 6, 6 plus CDMA models are not specified. Please let me know if the assumption is incorrect.

**Comment by InderKumarRathore** [comment]
I don't know dear if there is other strings for CDMA, though it should but I haven't received this request yet. Also I don't have these devices to test.

**Comment by thndrkiss** [comment]
Even am facing the same problem ! unable to find a 6 CDMA device to get the real model number ;).Thanks

**Comment by InderKumarRathore** [comment]
If you have CDMA device just run this code

`NSLog(@"%@", [DeviceUtil hardwareString]);`

and let me know the string. I searched on google but failed to get the string for CDMA device. I'm not sure but I think it should be same iPhone7,1 (for iPhone 6) and iPhone7,2 (for iPhone 6+)
