### ISSUE TITLE
Determine different simulators i.e. iPhone 6 and iPhone 6 plus

### ISSUE THREAD

**Issue by mcphersonjr** [InderKumarRathore/DeviceUtil#23]
Just thought I would bring up the issue of being able to determine the simulator hardware as a specific device rather than just "Simulator". One reason I bring this up is because in my application I need to present information to the user and change it depending on their device/screen size. I don't have an iPhone 6 plus to test the layout of the information on, and I need to use the simulator.

By the way, thanks for developing this utility.

**Comment by InderKumarRathore** [comment]
Hi Cedric McPherson,
For simulators we're getting the same string thus we can't differentiate between iPhone 6 and iPhone 6 Plus simulator. We can only know that it's a simulator.

**Comment by mrzystem** [comment]
@InderKumarRathore You can get the model identifier from the simulator as follows:

` if ([hardware isEqualToString:i386_Sim] || [hardware isEqualToString:x86_64_Sim]) {
      hardware = [[[NSProcessInfo processInfo] environment] objectForKey:@"SIMULATOR_MODEL_IDENTIFIER"];
  }`

**Comment by InderKumarRathore** [comment]
Thanks @mrzystem , Made changes related to it and pushed to `4.0.2`
