### ISSUE TITLE
Update Pods spec

### ISSUE THREAD

**Issue by iamcam** [InderKumarRathore/DeviceUtil#27]
The cocoa pods spec repo is out of date: https://github.com/CocoaPods/Specs/blob/master/Specs/UIDeviceUtil/1.1.2/UIDeviceUtil.podspec.json

**Comment by InderKumarRathore** [comment]
@iamcam I have created new repo for this i.e. DeviceUtil please check that https://cocoapods.org/?q=DeviceUtil

Initially this repos was UIDeviceUtil and then I renamed it to DeviceUtil, there was no way to rename the pod at cocoapods thus I have to create a new one. Sorry for the inconvenience
