### ISSUE TITLE
iPod 6 ? (iPod7,1)

### ISSUE THREAD

**Issue by Axadiw** [InderKumarRathore/DeviceUtil#28]
Could you add support for iPod 6th gen?

http://www.everymac.com/ultimate-mac-lookup/?search_keywords=iPod7,1

**Comment by awesomebing1** [comment]
I second this. It would be useful for my project!

**Comment by InderKumarRathore** [comment]
Solving it

**Comment by InderKumarRathore** [comment]
Please take 1.3.1 version

**Comment by InderKumarRathore** [comment]
@Axadiw @awesomebing1  sorry for delay was out of town, please take the lasted pod, thanks
