### ISSUE TITLE
Simulator with device ?

### ISSUE THREAD

**Issue by Jules2010** [InderKumarRathore/DeviceUtil#30]
I'm trying to develop for different devices and use the simulator to test my changes.

Will the DeviceUtil return simulator and the device ?

If it just returns simulator this isn't very useful.

**Comment by InderKumarRathore** [comment]
you can check wether the simulator is 64bit or 32bit, there is no more info that this or I assume any library can extract for a simulator

**Comment by Jules2010** [comment]
You can via inches, found this https://github.com/giuseppenucifora/UIDevice-Utils/issues/2#issuecomment-158789536

**Comment by InderKumarRathore** [comment]
Ah that can be done by checking the screen height or width as well, but this will tell you the screen size, it won't be able to tell you if your device is 5 or 5s :)

**Comment by Whirlwind** [comment]
@InderKumarRathore please check https://stackoverflow.com/questions/33493800/how-to-get-the-iphone-type-from-simulator-ios
