### ISSUE TITLE
DevicePlist not found in the bundle assertion.

### ISSUE THREAD

**Issue by eraydiler** [InderKumarRathore/DeviceUtil#35]
Hi, 

I'm getting this assertion because [deviceUtilBundle pathForResource:@"DeviceList" ofType:@"plist"] reurns nil. Another note to take account is that everything is ok on simulator, it just occures when i run the project on the device, iphone 5. What could cause this?

**Comment by InderKumarRathore** [comment]
It seems that the plist is not present either on DeviceUtil bundle or your
main bundle.

I would recommend you to use breakpoint and see why it's not picking the
plist?

P.S. I'm assuming you're using latest pod version

**Comment by taylanpince** [comment]
This was a pods installation error, removing the requirement and adding it back in solved the issue.

**Comment by weibel** [comment]
I'm seeing the same issue but in a different context.
I have multiple targets for link_with defined in my podfile. For all but the first target in the list the DeviceList.plist seems to be missing and the assertion fails.

**Comment by Michaelyb520** [comment]
Same problems as above. please see the screenshot, thanks. After running the "pod install", problems still exist.
![image](https://cloud.githubusercontent.com/assets/9857312/14731964/7d7defb0-0888-11e6-8d95-207fd2032dd7.png)

**Comment by InderKumarRathore** [comment]
Please run pod install again, it seems a cocoapod issue. If nothing works just add the plist file in your project. It will pick it from your resource bundle.

**Comment by Michaelyb520** [comment]
Problems still exist, it seems that cannot use cocoapods, because bundle resources package should be in the directory at the next higher level.
![image](https://cloud.githubusercontent.com/assets/9857312/14732155/561aecbe-088a-11e6-81cd-c2391f427a8d.png)

**Comment by InderKumarRathore** [comment]
As I said earlier it's a pod issue, I checked with my demo project and it's working fine.

What you can do is delete this pod from the pod file and run ```pod install```
After installation finishes re-add DeviceUtil pod and run ```pod install``` again

If problem still exists then run ```pod deintegrate``` and then ```pod install`` for fresh install

![screen shot 2016-04-22 at 10 42 03 am](https://cloud.githubusercontent.com/assets/352443/14732293/f188263a-0876-11e6-9d1a-6976f199638b.png)

**Comment by Michaelyb520** [comment]
Problems still exist.The following is my "Podfile" file content, and terminal operation process.
------------------------- content of the line --------------------------
![image](https://cloud.githubusercontent.com/assets/9857312/14732562/7b4f094e-088e-11e6-9be4-13b57bb693f0.png)
------------------------- content of the line --------------------------
![image](https://cloud.githubusercontent.com/assets/9857312/14732568/82e0f122-088e-11e6-90a1-8983da1d5b93.png)
------------------------- content of the line --------------------------
![image](https://cloud.githubusercontent.com/assets/9857312/14732575/98772c68-088e-11e6-93f1-6520bc1b7c8a.png)
------------------------- content of the line --------------------------
![image](https://cloud.githubusercontent.com/assets/9857312/14732581/a9a662f6-088e-11e6-9591-b42f27fa2533.png)

**Comment by InderKumarRathore** [comment]
Can you see the plist file in the pod directory?

**Comment by InderKumarRathore** [comment]
Also you need to do the following at the top of your pod file

**platform :ios, '8.0'**
**use_frameworks!**

Example
```
platform :ios, '8.0'
use_frameworks!

target 'PodTest' do
    pod 'DeviceUtil'
    pod 'Alamofire'
end
```

**Comment by KoD4K** [comment]
Update DeviceUtils to 1.3.7 version and have the same issue.
Stop at this line
`NSAssert(deviceList != nil, @"DevicePlist not found in the bundle.");`
Because 
`NSString *path = [deviceUtilBundle pathForResource:@"DeviceList" ofType:@"plist"];`
path is nil.
I see that DeviceList.plist does't copy to .app. Do u know how to fix it? Thanks!

**Comment by indrr78** [comment]
I don't know why this happens. I'll try and let you know. Also please check if you can do the same in a fresh sample project.

**Comment by InderKumarRathore** [comment]
I don't know why this happens. I'll try and let you know. Also please check if you can do the same in a fresh sample project.

**Comment by KoD4K** [comment]
I did it with sample project. Work fine. And this is bad for me.

**Comment by InderKumarRathore** [comment]
Try `pod update` or `pod install` again and let us know what worked for you.

**Comment by KoD4K** [comment]
It's also work fine with real device. But still doesn't work in simulator...

**Comment by InderKumarRathore** [comment]
Thanks @KoD4K for the solution
