### ISSUE TITLE
iPad Pro 9.7 hardware string

### ISSUE THREAD

**Issue by cliffjoyce** [InderKumarRathore/DeviceUtil#38]
iPad6,3 = iPad Pro 9.7" WiFi Only (128 GB)

[DeviceUtil logMessage:] [Line 233] This is a device which is not listed in this category. Please visit https://github.com/InderKumarRathore/DeviceUtil and add a comment there.
[DeviceUtil logMessage:] [Line 234] Your device hardware string is: iPad6,3

**Comment by Michaelyb520** [comment]
It's wrong.
![image](https://cloud.githubusercontent.com/assets/9857312/14731504/acac1ee2-0883-11e6-807a-f07ebc167027.png)

**Comment by InderKumarRathore** [comment]
What's your issue the pod or the value of iPad 9.7
