### ISSUE TITLE
iPad 5th generation support

### ISSUE THREAD

**Issue by alexanderlarionov** [InderKumarRathore/DeviceUtil#51]
Please add iPad 5th generation(Model A1822) to DeviceUtil.plist, enumeration and constants.
Thank you!

**Comment by InderKumarRathore** [comment]
Give me sometime, I'll refactor and add all the devices
Thanks

**Comment by InderKumarRathore** [comment]
Bumped the latest version, please let me know if you face some issues.
Thanks for your patience :)
