### ISSUE TITLE
New iPads 2017

### ISSUE THREAD

**Issue by alexanderlarionov** [InderKumarRathore/DeviceUtil#54]
Hello, can you add new released devices to DeviceUtil.plist, enumeration and constants, please?
iPad Pro 12.9"
iPad Pro 10.5"

Thank you!

**Comment by ityutin** [comment]
Yes, please! We're suffering without them :)

Thank you in advance!

**Comment by cliffjoyce** [comment]
Yes, please add the 2017 iPad Pros.  Thanks!

**Comment by cliffjoyce** [comment]
Your device hardware string is: iPad7,3 (for iPad Pro 10.5-inch).

**Comment by cliffjoyce** [comment]
@alexanderlarionov - attached is the version that I patched for the iPads that were released at WWDC17.  
[DeviceUtil with WWDC17 devices.zip](https://github.com/InderKumarRathore/DeviceUtil/files/1312166/DeviceUtil.with.WWDC17.devices.zip)

**Comment by crossle** [comment]
iPhone 8, plus

**Comment by InderKumarRathore** [comment]
Don’t have the hardware strings for these devices.

**Comment by InderKumarRathore** [comment]
Added iphone 8/plus/x strings

**Comment by cliffjoyce** [comment]
NSString* const iPad7_1 = @"iPad7,1";
  	NSString* const iPad7_2 = @"iPad7,2";
  	NSString* const iPad7_3 = @"iPad7,3";
  	NSString* const iPad7_4 = @"iPad7,4";

  	if ([hardware isEqualToString:iPad7_1])      return IPAD_PRO_12_2GEN_WIFI;
  	if ([hardware isEqualToString:iPad7_2])      return IPAD_PRO_12_2GEN_WIFI_CELLULAR;
  
  	if ([hardware isEqualToString:iPad7_2])      return IPAD_PRO_10_WIFI;
  	if ([hardware isEqualToString:iPad7_2])      return IPAD_PRO_10_WIFI_CELLULAR;

  	case IPAD_PRO_12_2GEN_WIFI:
  	case IPAD_PRO_12_2GEN_WIFI_CELLULAR:
  		  return CGSizeMake(4032, 3024);
  		  break;

      case IPAD_PRO_10_WIFI:
      case IPAD_PRO_10_WIFI_CELLULAR:
  		  return CGSizeMake(4032, 3024);
  		  break;
![ipad pro plist entries](https://user-images.githubusercontent.com/266027/31094377-d2dba17e-a769-11e7-9198-11d741abac42.png)
