### ISSUE TITLE
Need to add 11,1/11,3/11,5/11,7 (iPhone XS, XS Max or XR) devices

### ISSUE THREAD

**Issue by mtak-** [InderKumarRathore/DeviceUtil#59]
According to [this](https://bgr.com/2018/09/13/iphone-xs-max-vs-iphone-xr-a12-benchmark-scores-reveal-ram-details/) the "XS Max" will have the identifier `iPhone11,6` and the "XR" will have `iPhone11,8`. I am not sure what the regular "XS" will have as it's identifier.

**Comment by armandzwan** [comment]
See https://github.com/InderKumarRathore/DeviceUtil/pull/57

**Comment by Coeur** [comment]
I haven't seen `iPhone11,6` in the simulator. It was using `iPhone11,4` for the XS Max.
But it's totally possible that there are multiple references, especially when we openly know that there are distinct characteristics for the Chinese model and the non-Chinese one. There is a precedence with the iPhone 8, which had `iPhone10,1` for China and `iPhone10,4` for non-China.

**Comment by mtak-** [comment]
Ahh, how did I miss #57. Thanks for working on that. I'll leave the issue open, since it's unknown what the identifiers actually are.

**Comment by InderKumarRathore** [comment]
There are missing `11,1`, `11,3`,  `11,5`, `11,7` strings, although I couldn't find those devices on internet.
