### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by luoxiao** [InderKumarRathore/DeviceUtil#70]
## Hey, I am experiencing a bug, ARC environment, how can I encounter such a problem? what should I do?

--
![](https://ws4.sinaimg.cn/large/006tKfTcly1g0kapktf4oj31530u0gya.jpg)

**Comment by InderKumarRathore** [comment]
This seems old bug, where instance was de allocated, could you please tell me the version you are using and a sample if any
