### ISSUE TITLE
new 2019 devices

### ISSUE THREAD

**Issue by armandzwan** [InderKumarRathore/DeviceUtil#71]
Did anyone find the new 2019 device identifiers?
https://everymac.com/ultimate-mac-lookup/?search_keywords=Pending

**Comment by geometer** [comment]
iPhones ids: https://www.forbes.com/sites/gordonkelly/2019/07/23/apple-iphone-11-release-camera-upgrade-a13-iphone-xs-max-xr-update/. Maybe Chinese version codename is missing

**Comment by pikacode** [comment]
iPhone 11 hardwareDescription return nil, make me crash, maybe return @"" is better.

**Comment by InderKumarRathore** [comment]
Description is the name of the device if device is not listed it returns the nil, please check the nil.
iPhone 11/Pro/Max string added
