### ISSUE TITLE
Harware will never resolve to simulator

### ISSUE THREAD

**Issue by armandzwan** [InderKumarRathore/DeviceUtil#73]
At the beginning of
`- (Hardware)hardware { `
this is called:
`NSString *hardware = [self hardwareString];`

But since commit https://github.com/InderKumarRathore/DeviceUtil/commit/fa656df336d071dfdb4a733591ac5b8cde36da80 this will never return `i386_Sim` or `x86_64_Sim`.

Thus
```
if ([hardware isEqualToString:i386_Sim])     return SIMULATOR;
if ([hardware isEqualToString:x86_64_Sim])   return SIMULATOR;
```
will never happen.

Or am I missing something?

**Comment by InderKumarRathore** [comment]
yes ideally these statements should never run but if you check the hardwareString method in that there is a nil check and if that fails it will return the i386_Sim or x86_64_Sim
These are precautionary if checks

**Comment by armandzwan** [comment]
Ok, but how do you know that you are running on a simulator then?

**Comment by armandzwan** [comment]
What do you think of this?
https://github.com/InderKumarRathore/DeviceUtil/pull/74
