### ISSUE TITLE
hardware method disappeared

### ISSUE THREAD

**Issue by pnome** [InderKumarRathore/DeviceUtil#78]
The readme says to use

` DeviceUtil *deviceUtil = [[DeviceUtil alloc] init];
[deviceUtil hardwareString] == IPHONE_5`

to check the device type.

In 6.0.1 the hardware method has disappeared.  Is that a mistake, or should this be used in a different way now?

**Comment by InderKumarRathore** [comment]
Hardware method has been moved to extension not sure why it’s not visible

**Comment by pnome** [comment]
It works if I
`#import "DeviceUtil+Constant.h"`
instead of
`#import "DeviceUtil.h"`

**Comment by InderKumarRathore** [comment]
Hi pnome, I resolved this header problem. You can continue using `#import "DeviceUtil.h"` in `6.0.2`
Let me know if this doesn't work
