### ISSUE TITLE
Expected identifier

### ISSUE THREAD

**Issue by neuronuae** [InderKumarRathore/DeviceUtil#87]
Expected identifier in file 
<img width="1441" alt="Screen Shot 2020-10-22 at 10 00 43 AM" src="https://user-images.githubusercontent.com/60960730/96831151-9339ad00-144d-11eb-976b-2f49b79ad995.png">

**Comment by InderKumarRathore** [comment]
Hi @neuronuae are you still facing it? Because I can reproduce it.
