### ISSUE TITLE
Will there be a Cocoapod update that includes iPhone 12?

### ISSUE THREAD

**Issue by pnome** [InderKumarRathore/DeviceUtil#88]
Just wondering if the Pod will be updated to include the iPhone12

**Comment by InderKumarRathore** [comment]
Sorry, I thought I pushed the new version. It's cumbersome to maintain swift and Objective-C versions. Can you switch to swift versions of this lib? Link is provided in the readme file at top

**Comment by pnome** [comment]
Sure, no problem.  Thanks for getting back to me :)

**Comment by InderKumarRathore** [comment]
pushed
