### ISSUE TITLE
Support Apple Silicon Mac device identifiers?

### ISSUE THREAD

**Issue by cliffjoyce** [InderKumarRathore/DeviceUtil#89]
This may not be feasible, but it would be nice if DeviceUtil could report the macOS system and device info for iOS apps that are running on Apple Silicon Macs.  Currently, when the iOS app is run on an Apple Silicon Mac, DeviceUtil returns: iPad8,6 - iPad Pro 12.9-Inch 1TB (Wi-Fi Only - 3rd Gen).

**Comment by InderKumarRathore** [comment]
for that I need mac silicone to test and try out.

**Comment by chenzhenkui** [comment]
Support  Iphone14

**Comment by InderKumarRathore** [comment]
can you please migrate to https://github.com/InderKumarRathore/DeviceGuru
